version: '3.6'
services:


  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    environment:
      HOSTNAME: telegraf-mac-os
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      tick_net:
    depends_on:
      - influxdb


  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin123
      - INFLUXDB_ADMIN_PASSWORD=admin123
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      tick_net:


  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf_data:/var/lib/chronograf
    environment:
      RESOURCES_PATH: /usr/share/chronograf/resources
    networks:
      tick_net:
    links:
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      tick_net:
    volumes:
      - grafana_data:/var/lib/grafana

  
  kapacitor:
    image: kapacitor:latest
    volumes:
      - kapacitor_data:/var/lib/kapacitor
      - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    links:
      - influxdb
    networks:
      tick_net:



networks:
  tick_net:

volumes:
  influxdb_data:
  chronograf_data:
  kapacitor_data:
  grafana_data: