version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@docusaurus/core"
    versions:
    - 2.0.0-alpha.73
  - dependency-name: "@docusaurus/preset-classic"
    versions:
    - 2.0.0-alpha.71
    - 2.0.0-alpha.72
    - 2.0.0-alpha.73
  - dependency-name: "@docusaurus/theme-live-codeblock"
    versions:
    - 2.0.0-alpha.71
    - 2.0.0-alpha.72
    - 2.0.0-alpha.73
  - dependency-name: gridjs-react
    versions:
    - 3.4.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: classnames
    versions:
    - 2.3.0
  - dependency-name: faker
    versions:
    - 5.2.0
    - 5.5.0
    - 5.5.1
    - 5.5.2
  - dependency-name: "@types/faker"
    versions:
    - 5.5.0
